name: starter_kit_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2

  flutter:
    sdk: flutter
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  go_router: ^7.1.1
  hive: ^2.2.3
  injectable: ^2.1.2
  intl: ^0.18.0
  meta: ^1.9.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  lint: ^2.0.1
  injectable_generator: ^2.1.6
  very_good_analysis: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - .env
  fonts:
    - family: 'bold'
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: 'medium'
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: 'regular'
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
